name: Deploy to Apache Server

on:
  push:
    branches:
      - main  # Ajustar el nombre de la rama remota como se necesite - Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu

    steps:
      - name: Paso 01 Checkout repository
        uses: actions/checkout@v2

      - name: Paso 02 Configuracion de SHH - Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}

      - name: Paso 03 Agregar Servidor a lista de servidor conocidos - Add server to known_hosts
        run: |
          ssh-keyscan -H 18.223.99.169 >> ~/.ssh/known_hosts

      - name: Paso 04 Copiar Archivos PHP al directorio home - Copy PHP files to home directory
        run: |
          scp -r * ubuntu@18.223.99.169:/home/ubuntu/
        working-directory: ${{ github.workspace }}

      - name: Paso 05 Mover Archivos al directorio de apache y reiniciar apache - Move files to Apache directory and restart Apache
        run: |
          ssh ubuntu@18.223.99.169 'sudo mv /home/ubuntu/* /var/www/html/ && sudo systemctl restart apache2'
